version: '3'
volumes:  
  postgres_data: {} 
services:  
  base:    
    build:      
      context: .      
      dockerfile: ./docker/base/Dockerfile    
  app:    
    build:      
      context: .      
      dockerfile: ./docker/app/Dockerfile    
    depends_on:      
      - db
      - base
    ports:      
      - 2998:2998
  db:    
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
  web:    
    build:      
      context: .      
      dockerfile: ./docker/web/Dockerfile    
    depends_on:      
      - app    
    ports:      
      - 80:80
