default: &default
  mmt_url: http://docker.for.mac.host.internal:3000/api/collections
  cumulus_api: https://jtovpjptc7.execute-api.us-east-1.amazonaws.com/dev

development:
  <<: *default

test:
  <<: *default

sit:
  <<: *default
  mmt_url: https://sit-mmt.maap-project.org/api/collections

production:
  <<: *default
  mmt_url: https://mmt.maap-project.org/api/collections
