default: &default
  mmt_url: https://mmt.dit.maap-project.org/api/collections

development:
  <<: *default

test:
  <<: *default

dit:
  <<: *default
  mmt_url: https://mmt.dit.maap-project.org/api/collections

production:
  <<: *default
  mmt_url: https://mmt.maap-project.org/api/collections
