default: &default
  mmt_url: http://localhost:3001/api/collections
  cumulus_api: https://afoh1btrcd.execute-api.us-east-1.amazonaws.com/dev

development:
  <<: *default

test:
  <<: *default

production:
  mmt_url: https://mmt.maap-project.org/api/collections
