default: &default
  mmt_url: http://docker.for.mac.host.internal:3000/api/collections
  cumulus_api: https://jtovpjptc7.execute-api.us-east-1.amazonaws.com/dev

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  mmt_url: https://mmt.maap-project.org/api/collections
