default: &default
  mmt_url: http://docker.for.mac.host.internal:3000/api/collections

development:
  <<: *default

test:
  <<: *default

dit:
  <<: *default
  mmt_url: https://mmt.dit.maap-project.org/api/collections

sit:
  <<: *default
  mmt_url: https://sit-mmt.maap-project.org/api/collections

production:
  <<: *default
  mmt_url: https://mmt.maap-project.org/api/collections
