name: PR check

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '3 23 * * *' # daily

jobs:
  pre-commit-check:
    name: Pre-commit check to run bundle audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - run: bundle config set with 'development'
      - run: bundle install
      - run: bundle exec bundler-audit check  --update
      - run: bundle exec brakeman --no-pager
      # too many warnings for rubocop to be useful
      # - run: bundle exec rubocop .
